const supabaseUrl = 'https://gvbkdacpiiqkwsutbyqr.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2YmtkYWNwaWlxa3dzdXRieXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDc3MTksImV4cCI6MjA2Mjk4MzcxOX0.cWX8uKFDNDlvOF2zfwvXt1IzsqaPyxXEDhcSFCWcLuc';
window.supabase = Supabase.createClient(supabaseUrl, supabaseKey);